### ISSUE TITLE
Listing on rarity.tools

### ISSUE THREAD

**Issue by tartakovsky** [lobster-dao/overview#19]
Not my idea, but someone needed to make the issue.

Pros:
- additional exposure so people can find lobsters where people are already looking for other projects
- somewhat useful established rarity tool
- potentially fixable to include unminted lobsters (though I personally prefer not to include them into rarity calculations and instead to see how rare what is already there)

Cons:
- 2 ETH price

My argument to justify the cost goes as follows:
If listing on rarity.tools for 2 ETH will probably bring a 100 ETH more trading volume over a lifetime of LOBS because of additional exposure, then royalties bring 5.25 ETH to the DAO and the listing pays for itself.

**Comment by jshendrik** [comment]
> Pricy... can we just give them one of the NFTs from DAO? Instead of draining ETH treasury, expand the holder base. Because then even if they sell, it brings royalties to the DAO.

*checks the floor price*
No, I rather pay 2 ETH

**Comment by Fortuno89** [comment]
1 lobs is worth much more than 2 eth. And also, they are more of a limited resource, while eth will (hopefully) keep streaming into de treasury. My personal opinion is to hold giving out LOBS as much as we can.

**Comment by IvanGBi** [comment]
Imho, I might be wrong here. But this is how project treasuries work: if you give a contractor an asset, they might appreciate you more + do more work / end up never selling / end up joining a community. That's why there is carry in funds, equity for founders, etc. If you just flat-pay, you end up NOT growing the community. And you restrict royalty circulation as well. 

1 LOBS can end up being not sold + 2 ETH stays. Or ends up as sold then fine. ETH is there to spend then.

It's like using your shares to acquire talent. I understand this is trivial contract work, but I have had positive relationship with people when giving them assets instead of flat fees (even if it's more than they expect).

**Comment by tartakovsky** [comment]
Guess it's a valid argument. For the relationship to happen though someone would actually need to communicate to them and maintain that relationship. @IvanGBi wanna do the work? :)

**Comment by kkkrackpot** [comment]
I'd offer them 1 common LOBS.

**Comment by philippd8e** [comment]
any new?

**Comment by kkkrackpot** [comment]
Done.
Pls close.

**Comment by tartakovsky** [comment]
https://rarity.tools/lobsterdao
