### ISSUE TITLE
[Discussion] Bug: LobsterDAO NFT for project contributors

### ISSUE THREAD

**Issue by mdzor** [lobster-dao/overview#38]
LobsterDAO NFT for project contributors

During the initial distribution of LobsterNFT, some NFT were distributed to contributors who helped build the project.

Reference: https://docs.google.com/spreadsheets/d/1vjGXNyAMmudhZ6R7_qAPPs7RgES5DbMiiSAoeMnngw4/edit

Due to a bug in the script, some of those contributors have not received their attributed NFTs (from the extra tab). The bug appeared for those who provided the same address in the google sheet and to the Telegram bot.

Those affected have been identified and confirmed by the multi-sig participants.
For transparency, I am part of those impacted.

This GitHub thread is created to get your opinion on either the missing NFTs could be distributed in a randomized way to the 3 contributors impacted or not.

You may have noticed that I previously created a snapshot proposal, which I deleted in favor of this GitHub issue as recommended in Discord.

Cheers & good day!

**Comment by kkkrackpot** [comment]
Imo, it must be fixed somehow.

**Comment by tartakovsky** [comment]
Okay, CIA and others from the working group confirm that to be the case. Asked the artist, waiting for the answer. If everything checks out, then I propose we do a snapshot vote and distribute the missing LOBS from the 50 we minted recently.

**Comment by mdzor** [comment]
the above is confirmed via chat by the artist

**Comment by unknowablelobster** [comment]
Who are the members of the multi-sig, what's their relationship to @mdzor and @OffcierCia?

This proposal looks superficially like self-dealing and for the credibility of the project it's important that everything's squeaky clean.

**Comment by tartakovsky** [comment]
All three of them are on multisig, because all three of them have participated in launching the NFT. There are 11 other people on multisig, me, Ivan, banteg, etc included. I personally have no relationship with either of the receivers (or anyone else on the multisig) and aren't receiving anything through by facilitating this fix. There are no people on either the multisig or the working group who have found anything suspicious about the bug claim, everything seems to be in order and the mistake appears to be what mdzor claims it to be. Imo it's only natural that the person who is affected is also the person who has the attention and the initiative to find and raise the issue.

**Comment by unknowablelobster** [comment]
OK. Re-read my comment. 

I’m suggesting the “correction” should be handled in such a way that it builds confidence in the DAO and its leadership. 

It might *look* better if a) someone other than a beneficiary opened the proposal and b) it might have been beneficial to have high profile members of the multi-sig sign the proposal to signal its legitimacy. 

I have no view on whether the claim for additional NFTs is legitimate or otherwise. 

I do however believe good governance is a cornerstone of a successful enterprise, and I want to see the DAO succeed.

**Comment by tartakovsky** [comment]
I read your comment. High profile members of the multisig will probably sign, as I'm probably the only non-high-profile guy there. Re someone else opening the proposal: it is what it is, he found it, he opened it. Do you propose we delete his proposal and ask Ivan to re-open it so it _looks better_? I don't see how it is a better and more legitimate governance.

**Comment by unknowablelobster** [comment]
OK. 

I’ve done my bit by challenging the form of the proposal (note: not the substance) and by proposing improvements for future proposals.

**Comment by kkkrackpot** [comment]
I dont see anything wrong that @mdzor opened this "claim to hisself". He is interested in fixing the bug, indeed he opened this discussion. Pretty understandable, imo.
But also I'd like to see some 'high-profiles' confirming the bug. (I've seen enough actually, but maybe others want more)

**Comment by tartakovsky** [comment]
Done. The 28 LOBS were just distributed in sequential order. First 20 of the ones we have went to Klibansky, next 5 to CIA, next 3 to mdzor. Closing.
